### ISSUE TITLE
aws.ami_users configuration property doesn't work as expected

### ISSUE THREAD

**Issue by edie-z** [shinesolutions/packer-aem#162]
In the doc, it says aws.ami_users takes a list of AWS account IDs. 

But the below configuration gives me error:

  ami_users:
    - '<aws_account_id>'

'aws' errored: Error modify AMI attributes: InvalidAMIAttributeItemValue: Invalid attribute item value "[u'<aws_account_id>'] " for userId item type.
	status code: 400, request id: 7cfaf6b6-78d0-4600-8e5f-75a2e37b1f5f

I have to modify the configuration to be like this to make it work:
ami_users: '<aws_account_id>'

This means this property can only take one string type value.

**Comment by cliffano** [comment]
@edie-z Thanks for raising this issue.
The description was initially written that way to make it consistent with the documentation on Packer EBS volume itself that says "A list of account IDs..." .
Our documentation has been updated to say comma-separated-value since `aws.ami_users` is passed as a template variable which is then passed to an array-string configuration. https://www.packer.io/docs/templates/user-variables.html#using-array-values

Please feel free to re-open if there's any further issue.
