### ISSUE TITLE
Baking error on virtualenv installation 

### ISSUE THREAD

**Issue by hoomaan-kh** [shinesolutions/packer-aem#244]
**Describe the bug**
Baking failed when installing virtualenv.
here is error message
```Error: /Stage[main]/Config::Base/Config::Python_virtualenv[Config base python virtualenvs installation]/Pip::Install[virtualenv]/Exec[install-virtualenv]/returns: change from 'notrun' to ['0'] failed: 'pip2.7 install  virtualenv==16.7.9' returned 1 instead of one of [0]```

**To Reproduce**
1- make deps
2- make aws-java config_path=/path/to/config

**Expected behavior**
It should install virtualenv in baking step without error

**Screenshots**

**Environment (please complete the following information if relevant):**
 - Libraries and versions: [packer-aem master]
 - OS [rhel7,  jdk11, AEM65]

**Additional context**
N/A

**Comment by ovlords** [comment]
Issue was caused by an old Puppet module 'tracywebtech-pip'.  It attempted to install the virtualenv package and produced and error.  The module has not been improved since 2015.  

The '::python' class can be used to install the virtualenv package.  As a result, the function of installing the 'virtualenv' package can be taken over by the class.
